### ISSUE TITLE
Finds inside server autoruns use polling instead of oplog

### ISSUE THREAD

**Issue by etyp** [peerlibrary/meteor-reactive-mongo#3]
Originally from comment(s): https://github.com/peerlibrary/meteor-reactive-publish/issues/11#issuecomment-418943191

### Expected functionality
When using a `find` (or `findOne`, or anything which triggers a `fetch`) within a [server-side autorun](https://github.com/peerlibrary/meteor-server-autorun), I would expect that the find uses the oplog observe driver rather than polling.

For example, if I have:

```
Meteor.publish('messagesForGroup', function (groupId) {
  this.autorun(() => {
    const group = Groups.findOne(groupId, { fields: { members: 1 } });
    if (group.members.indexOf(this.userId) > -1) {
      return Messages.find({ group: group._id });
    }
  });
});
```

The expectation would be that the `Groups.findOne(groupId, { fields: { members: 1 } });` uses oplog.

### Actual functionality
The [reactive-mongo package adds](https://github.com/peerlibrary/meteor-reactive-mongo/blob/master/server.coffee#L49) `addedBefore` and `movedBefore` callbacks to `fetch`, `map` and `forEach` on cursors.

Because of this, it fails the first check in `observeChanges` in Meteor's [mongo_driver.js](https://github.com/meteor/meteor/blob/d8042c8fa9dd0cc53604b2729ac33333a2ce5b73/packages/mongo/mongo_driver.js#L1291) for whether or not it can use oplog.

The presence of `addedBefore` and `movedBefore` means that `ordered` returns true when the driver calls [LocalCollection._observeChangesCallbacksAreOrdered](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/minimongo/local_collection.js#L1361).

Therefore it is **never** possible in the current state to use oplog on cursors called from within a reactive context. They will always use polling.

**Comment by etyp** [comment]
@mitar thanks for the quick response on the other thread! I'm not super familiar with the oplog observer and why it's not meant to deal with `addedBefore` + `movedBefore` callbacks.

I've tried to hack something together to force `ordered = true` for finds called from within an active Tracker, but it feels dangerous without knowing _why_ oplog doesn't support those 2 callbacks.

Anyway, it's getting late here so I'll follow up with any other details in the morning. Let me know if you have any ideas or need help reproducing!

**Comment by etyp** [comment]
@mitar looked into this a bit more. Maybe it would make sense to only add the `addedBefore` + `movedBefore` invalidations in the following case:

```
options.skip || (options.limit && !options.sort)
```

This mirrors [OplogObserveDriver's](https://github.com/meteor/meteor/blob/d8042c8fa9dd0cc53604b2729ac33333a2ce5b73/packages/mongo/oplog_observe_driver.js#L958) check for whether oplog can be supported. What do you think?

**Comment by mitar** [comment]
So you are right that we should add those callbacks only when it is reasonable. But we should make sure to have a good check when is that reasonable. I think the issue here is that this is not clear from the query itself. So for example, if you have inside autorun something like `collection.find({}).fetch()` you might care about the order you are getting these out, or not. Now, we could say that if you cared about order, you should provide `sort` option, but this is not really a requirement.

I will have to think a bit more about this. Personally, I do not know why you would ever fetch more then one specific document inside autorun, but people might do M2M or something inside if they really want.

**Comment by etyp** [comment]
Yeah, I think maybe just excluding `addedBefore` and `movedBefore` callback booleans if the cursor is using sort/skip should work fine right? Because the only implication it would have is whether polling or oplog is used AFAICT --- it wouldn't impact the reactivity in the autorun, right?

Like:

```
callbacksUnordered =
  addedBefore: true
  removed: true
  changed: true
  movedBefore: true

callbacksOrdered =
  added: true
  changed: true
  removed: true

for method in ['forEach', 'map', 'fetch']
  do (method) ->
    originalMethod = MeteorCursor::[method]
    MeteorCursor::[method] = (args...) ->
      if @_isReactive()
        unordered = @skip || (@limit && !@sort)
        callbacks = if unordered then callbacksUnordered else callbacksOrdered
        @_depend callbacks
```

Since everyone using the package is using polling now, isn't it low-impact to add this and specify in readme that they should specify sort if they're using limit in order to leverage oplog?

Forgive me if I have this backwards - my coffeescript skills are non-existent and head is spinning from Meteor internals from the past few days 😆

**Comment by etyp** [comment]
@mitar so I'm working through this more, and am not really sure why anything aside from `added`, `changed` and `removed` should be reactive. What's the value of having `addedBefore` and `movedBefore` in there?

My assumption with using `find` inside an autorun would be that it re-runs on the same callbacks which are used in a cursor's `_publishCursor` (so just `added`, `changed`, `removed`).

Maybe I don't understand `addedBefore` and `movedBefore` well enough though.

Am I missing something?

**Comment by mitar** [comment]
The question boils down to: should `autorun` rerun if order of documents changes or not? if yes, you have to observe `addedBefore` and `movedBefore`, if not, then you do not have to.

It has nothing with the cursor you return from autorun.

The question is about reactive queries you make inside autorun, for example:

```js
this.autorun((computation) => {
  const myThirdFavoriteUser =  collection.Users.find().fetch()[3];

  return Posts.find({author: myThirdFavoriteUser._id});
});
```

Here, the order of returned users matter and the autorun should rerun if order changes. (Query is like that for demonstration purposes, of course you would use sort, skip and limit here otherwise.)
